---
- name: Install libraries using dnf
  become: yes
  dnf:
    state: present
    name:
      - curl
      - flatpak
      - git
      - java-1.8.0-openjdk-devel
      - java-11-openjdk-devel
      - maven
      - moby-engine
      - node
      - wget
      - yarn
