---
- name: Setup development environment
  hosts: localhost
  become: yes
  roles:
    - role: dnf
      tags:
        - library
    - role: flatpak
      tags:
        - flatpak
    - role: intellij
      tags:
        - intellij
