---
- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "{{ flathub_repo }}"

- name: Install application flatpaks
  community.general.flatpak:
    name: "{{ item.value }}"
    state: present
  loop: "{{ apps |  dict2items }}"
